name: Deploy dev to DigitalOcean

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MainnetURL: ${{ secrets.MainnetURL }}
      TestnetURL: ${{ secrets.TestnetURL }}
      WalletRoleURL: ${{ secrets.WalletRoleURL }}
      AkaDropURL: ${{ secrets.AkaDropURL }}
      TZKT_URL: ${{ secrets.TZKT_URL }}
      NEXT_PUBLIC_PARTNER_ID: ${{ secrets.NEXT_PUBLIC_PARTNER_ID }}
      NEXT_PUBLIC_BAUTH_USERNAME: ${{ secrets.NEXT_PUBLIC_BAUTH_USERNAME }}
      NEXT_PUBLIC_BAUTH_PASSWORD: ${{ secrets.NEXT_PUBLIC_BAUTH_PASSWORD }}
      NEXT_PUBLIC_DIRECTUS_ADMIN_EMAIL: ${{ secrets.NEXT_PUBLIC_DIRECTUS_ADMIN_EMAIL }}
      NEXT_PUBLIC_DIRECTUS_ADMIN_PASSWORD: ${{ secrets.NEXT_PUBLIC_DIRECTUS_ADMIN_PASSWORD }}
      GoogleMapsAPIKey: ${{ secrets.GoogleMapsAPIKey }}
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      WALLET_PASSPHRASE: ${{ secrets.WALLET_PASSPHRASE }}
      SERVER_URL: ${{ secrets.SERVER_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.0

      - name: Install dependencies and build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_ed25519
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy dev to DigitalOcean
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            # Source NVM and use Node.js 20.8.0
            export NVM_DIR=\$HOME/.nvm
            [ -s \$NVM_DIR/nvm.sh ] && \. \$NVM_DIR/nvm.sh
            nvm use 20.8.0

            # Install PM2 globally if not exists
            npm install -g pm2

            # Properly clean up existing PM2 process
            pm2 delete open-road-demo-next-dev || true
            
            # Clean up and prepare directory with sudo
            sudo rm -rf /var/www/dev.kairos-mint.art
            sudo mkdir -p /var/www/dev.kairos-mint.art
            sudo chown -R \$USER:\$USER /var/www
            sudo chmod -R 755 /var/www
            
            # Clone the repository
            cd /var/www
            git clone https://github.com/PIMIYA/open-road-demo-next.git dev.kairos-mint.art
            cd dev.kairos-mint.art

            # Create .env and .env.local files
            cat > .env << 'EOL'
            MainnetURL=${MainnetURL}
            TestnetURL=${TestnetURL}
            WalletRoleURL=${WalletRoleURL}
            AkaDropURL=${AkaDropURL}
            TZKT_URL=${TZKT_URL}
            NEXT_PUBLIC_PARTNER_ID=${NEXT_PUBLIC_PARTNER_ID}
            NEXT_PUBLIC_BAUTH_USERNAME=${NEXT_PUBLIC_BAUTH_USERNAME}
            NEXT_PUBLIC_BAUTH_PASSWORD=${NEXT_PUBLIC_BAUTH_PASSWORD}
            NEXT_PUBLIC_DIRECTUS_ADMIN_EMAIL=${NEXT_PUBLIC_DIRECTUS_ADMIN_EMAIL}
            NEXT_PUBLIC_DIRECTUS_ADMIN_PASSWORD=${NEXT_PUBLIC_DIRECTUS_ADMIN_PASSWORD}
            GoogleMapsAPIKey=${GoogleMapsAPIKey}
            WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
            WALLET_PASSPHRASE=${WALLET_PASSPHRASE}
            SERVER_URL=${SERVER_URL}
            PORT=3002
            EOL

            # Copy .env to .env.local
            cp .env .env.local
            
            # Install dependencies and build
            npm install --legacy-peer-deps
            npm run build
            
            # Start PM2 with the correct environment and port
            PORT=3002 pm2 start npm --name 'open-road-demo-next-dev' -- start
            
            # Save PM2 configuration to persist across reboots
            pm2 save
          "




          