name: Deploy dev to DigitalOcean

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy dev to DigitalOcean
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /var/www/dev.kairos-mint.art &&
            git pull origin dev &&
            npm install &&
            npm run build &&
            pm2 restart open-road-demo-next-dev
          "
          rm id_rsa # Remove the private key after use
